"""
This type stub file was generated by pyright.
"""

"""Utility functions for working with collection types."""
def update_multimap(multimap: dict, key, value): # -> bool:
    """
    Add a value to a multimap

    :param multimap: the multimap to update
    :param key: key in the multimap
    :param value: value to add for the key
    :return: bool, whether a value was already present for the key
    """
    ...

