"""
This type stub file was generated by pyright.
"""

'''Functions to be called from applications to help support testing

These utilities are not contained in dgutil.testing since that would potentially
cause a circular dependency.
'''
def get_test_token(): # -> str:
    """
    Get a pseudo-random token to test data flowing in and out of storage

    :return: a pseudo-random token
    :rtype: str
    """
    ...

class Link:
    """
    Represents a symlink within a mock filesystem
    """
    def __init__(self, target) -> None:
        ...
    


class Grep:
    """
    Wrap expected output in this class to search for the term in the output
    rather than matching the entire string.
    """
    def __init__(self, search) -> None:
        ...
    


class JSONFilter:
    """
    Filter JSON output by removing certain keys
    """
    def __init__(self, remove, text) -> None:
        ...
    
    def applyFilter(self, output): # -> str:
        ...
    


def filterJSONRecursive(jsonObj, keysToRemove): # -> dict[Any, Any] | list[Any]:
    """
    Recursively remove keys from a JSON object
    """
    ...

