"""
This type stub file was generated by pyright.
"""

"""Utility functions for type-checking"""
def empty(value): # -> bool:
    """
    Emptiness check, polymorphic over None, str and list

    :param value: value to check for emptiness
    """
    ...

def nonempty(value): # -> bool:
    """Non-emptiness check, inverse of `empty`"""
    ...

def type_error(varname, actual_typename, expected_typename):
    ...

def has_type(val, typ): # -> TypeIs[Callable[..., object]] | bool:
    ...

def type_check(val, typ, varname): # -> None:
    ...

